### ISSUE TITLE
MIT License from 2017?

### ISSUE THREAD

**Issue by markstur** [IBM/pytorch-on-watson-studio#10]
Is that MIT License there because this is a 2017 asset that was licensed?  If that is just a copy/paste thing then we want to use apache2 there (correct the year?).

**Comment by markstur** [comment]
@yinchen-ibm couldn't assign you for some reason, but please take a look.

**Comment by yinchen-ibm** [comment]
I believe that MIT license is from the original notebook created by Lucasz, I don't know if we should re-license it apache2 @rhagarty what's our policy for code pattern?

**Comment by markstur** [comment]
Keeping MIT and adding ACK w/ info.
Fixed in #19
